[snowflake]
account = "TQGBAWL-AQ10671"
user = "KIWIKODE"
api_key = "eyJraWQiOiI1MDY3OTY2NDY0NSIsImFsZyI6IkVTMjU2In0.eyJwIjoiMTk3OTY3MzY0OjUwNjc5NjQ0NDIxIiwiaXNzIjoiU0Y6MTAxNiIsImV4cCI6MTc3MjkxOTA4NX0.LIKDo2qV_IftVEcaWc8WFicCNlDfWy-7xaLULA9-i7ztGDNjM0F_KO7Wf7pZw6hQstG90lMsLZxNz-tvlqGODw"
role = "ACCOUNTADMIN"
host = "TQGBAWL-AQ10671.snowflakecomputing.com"
